baseURL: "https://wpiesports.github.io/"
title: WPI Esports
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "WPI Esports"
  description: "Esports at Worcester Polytechnic Institute"
  keywords: [WPI, Esports, Worcester]
  images: ["/logo.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  label:
    text: "WPI Esports"
    icon: /logo.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: WPI Esports
    subtitle: "Worcester Polytechnic Institute's Esports Club"
    imageUrl: "/logo.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: WPI Esports Logo
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Welcome to WPI Esports!"
    Content: > 
      We compete in intercollegiate tournaments, host local events, and provide other esports opportunities for the WPI community. Recently we opened the Esports Lab which you can read about [here](/esports_lab). If you're interested in our community, check out the socials below or the articles on this website.<br /><br /><iframe width=100% height="405" src="https://www.youtube.com/embed/n3IdnYgl2sY?&autoplay=1&mute=1&start=18448" title="Valorant Tournament" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  socialIcons:
    - name: discord
      url: "https://discord.gg/WJ8gEcd"
    - name: twitter
      url: "https://twitter.com/wpiesports"
    - name: instagram
      url: "https://instagram.com/wpiesports"
    - name: youtube
      url: "https://www.youtube.com/channel/UCy-L_lTEMaxCBcahqtZSRjg?ltclid="
    - name: twitch
      url: "https://twitch.tv/wpiesports"
    - name: email
      url: "mailto:gr-esports-exec@wpi.edu"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: about
      name: "About"
      url: /about/
      weight: 10
    - identifier: esports-lab
      name: "Esports Lab"
      url: /esports_lab
      weight: 10
    - identifier: teams
      name: "Teams"
      url: /teams/
      weight: 20
    - identifier: events
      name: "Events"
      url: /events/
      weight: 30
    - identifier: staff
      name: "Staff"
      url: /staff/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
